### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by johnhaley81** [pusher/atom-pair#1]
1. Open a file
2. Join session with another user
3. Close that file.
4. Error!

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v0.27.0
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1007

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1007:15)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:661:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2673:33)
  at Object.module.exports.AtomPair.changeBuffer (/Users/johnh/.atom/packages/atom-pair/lib/atom_pair.coffee:281:15)
  at /Users/johnh/.atom/packages/atom-pair/lib/atom_pair.coffee:236:10
  at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:103:9)
  at /Users/johnh/.atom/packages/atom-pair/lib/atom_pair.coffee:235:9
  at PresenceChannel.prototype.emit (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:3713:6)
  at PresenceChannel.prototype.handleEvent (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:3831:51)
  at /Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/Users/johnh/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```
### Commands

```
     -1:40.9 refactor:done (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -1:40.9 editor:newline (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -1:40.5 refactor:done (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -1:40.5 editor:newline (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -1:36.0 editor:move-to-first-character-of-line (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -1:34.6 editor:move-to-end-of-screen-line (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
  2x -1:23.4 editor:select-to-beginning-of-word (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:26.0 refactor:done (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:26.0 editor:newline (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:25.9 refactor:done (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:25.9 editor:newline (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:25.5 refactor:done (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:25.5 editor:newline (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
  7x -0:19.6 core:backspace (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:09.7 core:move-right (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
     -0:09.3 core:backspace (atom-text-editor#AtomPair.editor.vim-mode.insert-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap-git-diff",
      "gitter"
    ],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-pair, v0.27.0
clang-format, v1.7.0
editorconfig, v0.3.0
js-refactor, v0.3.0
linter, v0.11.1
minimap, v4.1.0
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v3.1.0
minimap-highlight-selected, v4.0.0
minimap-selection, v3.1.1
react, v0.9.8
refactor, v0.4.1
script, v2.16.0
seti-ui, v0.6.3
travis-ci-status, v0.11.2
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by jpatel531** [comment]
Is this problem still ex

**Comment by jpatel531** [comment]
v 0.0.28 - released just now - should have solved this. Are you still experiencing the problem?

**Comment by johnhaley81** [comment]
Cool! It's working. Canceling the session is a good solution. Thanks jpatel531.

**Comment by hdtafur** [comment]
I'm currently experiencing this problem.

`Error: This TextEditor has been destroyed at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition`

**Comment by aldialimucaj** [comment]
am also having this issue on Atom v0.189.0

**Comment by jpatel531** [comment]
v1.1.4 has been released, where this error does not occur. Thanks!! :)
