### ISSUE TITLE
Throws an error when someone connects

### ISSUE THREAD

**Issue by Xendergo** [pusher/atom-pair#125]
this is the error, I hope someone can fix it because my friend cant pair with me on atom

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package 2.0.12

### Stack Trace

Uncaught TypeError: Cannot read property 'clearIndicators' of undefined

```
At C:\Users\hrovn\.atom\packages\atom-pair\lib\modules\session.coffee:157

TypeError: Cannot read property 'clearIndicators' of undefined
    at /packages/atom-pair/lib/modules/session.coffee:157:11
    at PresenceChannel.prototype.emit (/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at PresenceChannel.prototype.handleEvent (/packages/atom-pair/lib/pusher/pusher.js:3827:12)
    at /packages/atom-pair/lib/pusher/pusher.js:74:9
    at ConnectionManager.prototype.emit (/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at message (/packages/atom-pair/lib/pusher/pusher.js:3420:6)
    at Connection.prototype.emit (/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at message (/packages/atom-pair/lib/pusher/pusher.js:3048:8)
    at TransportConnection.prototype.emit (/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at TransportConnection.prototype.onMessage (/packages/atom-pair/lib/pusher/pusher.js:2210:6)
    at WebSocket.self.socket.onmessage (/packages/atom-pair/lib/pusher/pusher.js:2232:6)
```

### Commands

```
  2x -2:43.6.0 core:backspace (input.hidden-input)
     -2:38.6.0 atom-save-all:saveAll (input.hidden-input)
  3x -2:26.1.0 core:backspace (input.hidden-input)
     -2:19.5.0 atom-save-all:saveAll (input.hidden-input)
     -2:00.8.0 core:copy (input.hidden-input)
  2x -1:59.5.0 editor:newline (input.hidden-input)
     -1:59 core:paste (input.hidden-input)
     -1:54.8.0 core:move-right (input.hidden-input)
  3x -1:54.5.0 core:backspace (input.hidden-input)
  2x -1:49.7.0 editor:newline (input.hidden-input)
     -1:49.2.0 core:paste (input.hidden-input)
  6x -1:45.8.0 core:backspace (input.hidden-input)
  2x -1:37.4.0 atom-save-all:saveAll (input.hidden-input)
  4x -1:03.2.0 core:backspace (input.hidden-input)
     -0:56.3.0 AtomPair:start new pairing session (input.hidden-input)
     -0:37.7.0 atom-save-all:saveAll (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-pair 2.0.12 
atom-save-all 0.4.1 
```

**Comment by kn100** [comment]
Could you please update your plugins and try again? There was recently a new version.
