### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by ghost** [pusher/atom-pair#16]
[Enter steps to reproduce below:]
1. Testing out joining a pairing session through HipChat to myself
2. After asking for the @mention name is threw the error - but still sent to HipChat

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v0.37.0
### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/aaron/.atom/packages/atom-pair/lib/atom_pair.coffee:162

TypeError: Cannot read property 'buffer' of undefined
  at Object.module.exports.AtomPair.startPairing (/Users/aaron/.atom/packages/atom-pair/lib/atom_pair.coffee:162:31)
  at /Users/aaron/.atom/packages/atom-pair/lib/modules/hipchat_invite.coffee:55:10
  at IncomingMessage.<anonymous> (/Users/aaron/.atom/packages/atom-pair/node_modules/node-hipchat/lib/hipchat.js:226:24)
  at IncomingMessage.emit (events.js:138:20)
  at _stream_readable.js:909:16
  at process._tickCallback (node.js:364:11)

```
### Commands

```
     -6:23.9 window:increase-font-size (div.settings-view.pane-item)
  3x -6:23.5 settings-view:open (div.settings-view.pane-item)
     -2:16.5 core:paste (atom-text-editor#atom-pair.hipchat_token.editor.mini)
  6x -2:14.1 core:backspace (atom-text-editor#atom-pair.hipchat_room_name.editor.mini)
     -1:47.6 command-palette:toggle (atom-text-editor.editor)
  2x -1:46.2 core:backspace (atom-text-editor.editor.mini)
     -1:45.2 core:select-all (atom-text-editor.editor.mini)
  3x -1:45.0 core:backspace (atom-text-editor.editor.mini)
  2x -1:36.1 core:move-down (atom-text-editor.editor.mini)
     -1:35.2 core:confirm (atom-text-editor.editor.mini)
     -1:35.2 AtomPair:invite over hipchat (atom-text-editor.editor)
  6x -1:29.6 core:backspace (atom-text-editor.editor)
     -0:01.8 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {},
  "atom-pair": {
    "hipchat_token": "4407a1d5f54e3a5e9bce1751d8754c",
    "hipchat_room_name": "Uidaho"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v0.37.0
autocomplete-plus, v2.1.6
minimap, v4.2.2

# Dev
No dev packages
```

**Comment by ghost** [comment]
What was the resolution to this?  I'm trying to integrate Slack and it's throwing the same error for me.
