### ISSUE TITLE
setConfig was removed which causes command AtomPair:set configuration keys to fail

### ISSUE THREAD

**Issue by halrlee** [pusher/atom-pair#19]
In file lib/atom_pair.coffee the line that is adding the subscription for the command to set configuration keys fails because a recent commit removed that function from the 
lib/modules/atom_pair_config.coffee

https://github.com/pusher/atom-pair/commit/e22c7ed8f08e5d6297c681f80e1a9a5e67c98829#diff-958530e2b858f36af5553c016b9add65

Just need to comment out this line in the file or create some other action that will load the Package/Settings page. I did a quick look but didn't see anything that jumped out. 
https://github.com/atom/settings-view/tree/master/lib

@subscriptions.add atom.commands.add 'atom-workspace', 'AtomPair:set configuration keys': => @setConfig()

Get a nasty red box when that command is selected. 

[Enter steps to reproduce below:]
1. Ctrl-Shift-P
2. Select AtomPair:set configuration keys

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v0.37.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/HL180000/.atom/packages/atom-pair/lib/atom_pair.coffee:51

TypeError: undefined is not a function
    at atom-workspace.subscriptions.add.atom.commands.add.AtomPair:set configuration keys (/Users/HL180000/.atom/packages/atom-pair/lib/atom_pair.coffee:76:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
```
### Commands

```
     -0:03.7 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:01.6 core:move-down (atom-text-editor.editor.mini)
     -0:00.8 core:confirm (atom-text-editor.editor.mini)
     -0:00.8 AtomPair:set configuration keys (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-pair": {
    "pusher_app_key": "<nope>",
    "pusher_app_secret": "<not gonna show you>"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v0.37.0

# Dev
No dev packages
```

**Comment by snollygolly** [comment]
I was able to get the settings page to open via:

```
  setConfig: ->
    configUri = 'atom://config'
    return atom.workspace.open("" + configUri + "/packages")
```

but I wasn't able to figure out how to open up atom-pair's settings.
