### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by lancelafontaine** [pusher/atom-pair#27]
The following error happens every time I try to join another's session. 
Running Atom v0.187.0 on Ubuntu 14.04.

[Enter steps to reproduce below:]
1. `Ctrl + Shift + P`, then select `AtomPair: Join pairing session`
2. Receive the following error message: `undefined. home/lance/.atom/packages/atom-pair//lib/atom_pair.coffee:114`. The error was thrown from the atom-pair package. You can help by creating an issue. Please explain what actions triggered this error.

**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /home/lance/.atom/packages/atom-pair/lib/atom_pair.coffee:114

TypeError: Cannot read property 'then' of undefined
  at space-pen-div.<anonymous> (/home/lance/.atom/packages/atom-pair/lib/atom_pair.coffee:114:28)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -0:11.6 tree-view:toggle (atom-text-editor.editor)
     -0:06.1 command-palette:toggle (atom-text-editor.editor)
     -0:02.3 core:move-down (atom-text-editor.editor.mini)
     -0:02.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.0 AtomPair:join pairing session (atom-text-editor.editor)
     -0:01.3 core:paste (atom-text-editor.editor.mini)
     -0:01.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "graphite-ui",
      "monokai"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "emmet-atom"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-open-recent, v2.2.0
atom-pair, v1.0.1
autocomplete-plus, v2.5.0
graphite-ui, v0.14.1
language-html, v0.29.0
language-latex, v0.4.1
language-python, v0.32.0
latex, v0.19.1
linter, v0.12.0
linter-csslint, v0.0.11
linter-flake8, v1.3.0
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-shellcheck, v0.0.7
linter-tidy, v1.0.0
minimap, v4.6.0
monokai, v0.12.0
pdf-view, v0.17.0
save-session, v0.12.0
trailing-spaces, v0.2.4

# Dev
No dev packages
```

**Comment by hellsan631** [comment]
This was happening a session today whenever the host opened up an existing file. I would get a blank file in a new window and Atom would throw this error. There was only 1 file open when I connected.
