### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by mingraham** [pusher/atom-pair#33]
[Enter steps to reproduce below:]
1. Configure Webhook Integration for Slack to #general.
2. Add the Webhook URL (I assumed this was the Token) to the "WebHook URL for Slack Incoming Webhook Integration" of the atom-pair configuration.
3. Try to collaborate with someone using "AtomPair: Invite Over Slack"

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v1.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'statusCode' of undefined

```
At /Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/lib/lib/slack.seed.js:58

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/lib/lib/slack.seed.js:58:25)
    at self.callback (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/node_modules/request/request.js:121:22)
    at Request.emit (events.js:116:17)
    at Request.self._buildRequest (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/node_modules/request/request.js:336:39)
    at Request.init (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/node_modules/request/request.js:503:10)
    at new Request (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/node_modules/request/request.js:97:8)
    at request (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/node_modules/request/index.js:50:11)
    at Function.request.post (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/node_modules/request/index.js:116:27)
    at Slack.webhook (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/lib/lib/slack.seed.js:52:20)
    at Slack.webhook (/Users/mingraham/.atom/packages/atom-pair/node_modules/slack-node/lib/lib/slack.seed.js:3:59)
```
### Commands

```
     -0:14.0 command-palette:toggle (atom-text-editor.editor)
  5x -0:09.3 core:move-left (atom-text-editor.editor.mini)
     -0:08.4 core:backspace (atom-text-editor.editor.mini)
     -0:07.3 core:move-down (atom-text-editor.editor.mini)
     -0:06.8 core:confirm (atom-text-editor.editor.mini)
     -0:06.8 AtomPair:invite over slack (atom-text-editor.editor)
     -0:00.4 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "atom-pair": {
    "slack_url": "Uh5agJemavWUnV8J8OiBxqpX"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v1.1.2

# Dev
No dev packages
```

**Comment by jpatel531** [comment]
Hi there!

I think your slack url should be in the format: "https://hooks.slack.com/services/" + token

Let me know if this works :)

**Comment by mingraham** [comment]
This stopped the error! Thank you so much. Though now I tried to invite my friend using @<name_here> and he never got an invitation on Slack. Any ideas?

**Comment by jpatel531** [comment]
Ah, I had this problem too the other day. It worked for #general - I just sent one now to myself (using "@" + username) and it came from 'slackbot'. I'll get my colleague to send me an invite :)

**Comment by jpatel531** [comment]
(the problem seemed to be that i tried to send an invite to another account - but it only worked for #general and, now, myself )

**Comment by mingraham** [comment]
Mine does not even work for #general and myself. Interesting. What did you do to get that working?

**Comment by jpatel531** [comment]
Just to make sure, do you have incoming webhooks on slack set up?

**Comment by jpatel531** [comment]
Hmm, I basically just followed the steps in @snollygolly 's amendment to the README. Basically what you did:  set up the incoming webhook on slack (the name of the channel shouldn't matter I think), get your webhook url and put enter it on the settings page, then send with '#' + channel or '@' + user. It all works swimmingly over here :confused:

**Comment by mingraham** [comment]
I found the source of the issue: I did not copy over the Slack URL correctly. It works great, thanks for your help!

**Comment by jpatel531** [comment]
Sweet! :D
