### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pasteText' of undefined

### ISSUE THREAD

**Issue by adamsoffer** [pusher/atom-pair#35]
[Enter steps to reproduce below:]
1. Create new file
2. Click AtomPair: Custom Paste

**Atom Version**: 0.176.0
**System**: Mac OS X 10.90
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v1.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'pasteText' of undefined

```
At /Users/ads1018/.atom/packages/atom-pair/lib/modules/custom_paste.coffee:16

TypeError: Cannot read property 'pasteText' of undefined
  at Object.module.exports.CustomPaste.customPaste (/Users/ads1018/.atom/packages/atom-pair/lib/modules/custom_paste.coffee:16:14)
  at atom-workspace.subscriptions.add.atom.commands.add.AtomPair:custom-paste (/Users/ads1018/.atom/packages/atom-pair/lib/atom_pair.coffee:74:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/ads1018/.atom/packages/motepair/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/Users/ads1018/.atom/packages/motepair/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Users/ads1018/.atom/packages/motepair/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLOListElement.elemData.handle (/Users/ads1018/.atom/packages/motepair/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
     -2:35.0 core:select-all (atom-text-editor.editor.mini)
     -2:26.9 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:57.6 core:select-all (atom-text-editor.editor.mini)
     -0:32.5 core:close (div.markdown-preview.native-key-bindings)
     -0:06.2 command-palette:toggle (atom-pane.pane.active)
     -0:04.1 core:backspace (atom-text-editor.editor.mini)
     -0:01.5 AtomPair:custom-paste (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {},
  "atom-pair": {
    "hipchat_token": "570f5036303c82835e9248c6d018ee",
    "hipchat_room_name": "Lego Star Wars",
    "pusher_app_key": "9f048679e0e2c91034dc",
    "pusher_app_secret": "4859833bca7c1fb2b0b2"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v1.1.2
emmet-atom, v2.3.4
linter, v0.12.0
linter-jscs, v1.9.0
motepair, v0.18.0
react, v0.9.11
resize-indent, v0.2.1
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by jpatel531** [comment]
Version 1.1.3 should now have resolved this issue =)
