### ISSUE TITLE
Failed to activate the atom-pair package

### ISSUE THREAD

**Issue by jcausey-astate** [pusher/atom-pair#37]
[Enter steps to reproduce below:]
1. ... Upgraded from 1.1.1
2. ... Upgraded Atom to most recent version
3. ... Re-started Atom - Error dialog with "Cannot find module 'space-pen'" appears.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v1.1.3
### Stack Trace

Failed to activate the atom-pair package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/jcausey/.atom/packages/atom-pair/lib/views/atom-pair-view.coffee:6:10)
    at Object.<anonymous> (/Users/jcausey/.atom/packages/atom-pair/lib/views/atom-pair-view.coffee:37:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "markdown-format",
      "markdown-preview",
      "build",
      "go-plus"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v1.1.3
atom-runner, v2.3.0
auto-detect-indentation, v0.3.0
autocomplete-plus, v2.7.1
compare-files, v0.4.1
go-format, v1.0.7
go-rename, v0.3.0
language-latex, v0.4.1
language-mediawiki, v0.1.0
latex, v0.20.0
linter, v0.12.0
markdown-preview-plus, v1.3.0
mathjax-wrapper, v0.1.0
monokai, v0.13.0
pdf-view, v0.17.0
pretty-json, v0.3.2
remote-edit, v1.7.2
remote-sync, v2.4.1
save-session, v0.12.5
script, v2.18.0
sync-settings, v0.2.2
tabs-to-spaces, v0.9.0
texlicious, v0.3.9

# Dev
No dev packages
```

**Comment by jcausey-astate** [comment]
Actually, I notice that the automatic update of Atom didn't take -- it was still on 0.187.0, so I manually downloaded and installed 0.189.0.
Error is still present:

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v1.1.3

### Stack Trace

Failed to activate the atom-pair package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jcausey/.atom/packages/atom-pair/lib/views/atom-pair-view.coffee:1:10)
  at Object.<anonymous> (/Users/jcausey/.atom/packages/atom-pair/lib/views/atom-pair-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jcausey/.atom/packages/atom-pair/lib/views/start-view.coffee:1:16)
  at Object.<anonymous> (/Users/jcausey/.atom/packages/atom-pair/lib/views/start-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.AtomPair.activate (/Users/jcausey/.atom/packages/atom-pair/lib/atom_pair.coffee:50:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:445:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:343:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:52:25)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "markdown-format",
      "markdown-preview",
      "build",
      "go-plus"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-pair, v1.1.3
atom-runner, v2.3.0
auto-detect-indentation, v0.3.0
autocomplete-plus, v2.7.1
compare-files, v0.4.1
go-format, v1.0.7
go-rename, v0.3.0
language-latex, v0.4.1
language-mediawiki, v0.1.0
latex, v0.20.0
linter, v0.12.0
markdown-preview-plus, v1.3.0
mathjax-wrapper, v0.1.0
monokai, v0.13.0
pdf-view, v0.17.0
pretty-json, v0.3.2
remote-edit, v1.7.2
remote-sync, v2.4.1
save-session, v0.12.5
script, v2.18.0
sync-settings, v0.2.2
tabs-to-spaces, v0.9.0
texlicious, v0.3.9

# Dev
No dev packages
```

**Comment by jpatel531** [comment]
Does this issue persist? What happens if you go into the repo at ~/.atom/packages and npm install there?

**Comment by jcausey-astate** [comment]
No, the issue seems to be fixed for Atom (v1.0.5) + atom-pair (v2.0.5).
Thanks!

**Comment by eikooc** [comment]
The issue is back :-)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package 2.0.10


### Stack Trace

Failed to activate the atom-pair package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Ajv.localCompile (/packages/atom-pair/node_modules/ajv/lib/compile/index.js:139:26)
    at Ajv.resolve (/packages/atom-pair/node_modules/ajv/lib/compile/resolve.js:53:19)
    at Object.resolveRef (/packages/atom-pair/node_modules/ajv/lib/compile/index.js:210:21)
    at /packages/atom-pair/node_modules/ajv/lib/dotjs/ref.js:22:22)
    at /packages/atom-pair/node_modules/ajv/lib/dotjs/validate.js:156:37)
    at /packages/atom-pair/node_modules/ajv/lib/dotjs/properties.js:199:26)
    at generate_validate (/packages/atom-pair/node_modules/ajv/lib/dotjs/validate.js:229:37)
    at localCompile (/packages/atom-pair/node_modules/ajv/lib/compile/index.js:99:22)
    at Ajv.compile (/packages/atom-pair/node_modules/ajv/lib/compile/index.js:67:13)
    at _compile (/packages/atom-pair/node_modules/ajv/lib/ajv.js:328:29)
    at getSchema (/packages/atom-pair/node_modules/ajv/lib/ajv.js:192:51)
    at validate (/packages/atom-pair/node_modules/ajv/lib/ajv.js:91:11)
    at validateSchema (/packages/atom-pair/node_modules/ajv/lib/ajv.js:162:19)
    at _addSchema (/packages/atom-pair/node_modules/ajv/lib/ajv.js:288:7)
    at addSchema (/packages/atom-pair/node_modules/ajv/lib/ajv.js:133:26)
    at addInitialSchemas (/packages/atom-pair/node_modules/ajv/lib/ajv.js:396:39)
    at /packages/atom-pair/node_modules/ajv/lib/ajv.js:78:3)
    at /packages/atom-pair/node_modules/har-validator/lib/node4/promise.js:43:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-pair/node_modules/request/lib/har.js:5:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
     -0:01.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-pair 2.0.10 
atom-typescript 10.1.14 
editorconfig 2.2.0 
language-vue 0.21.2 
linter 1.11.22 
linter-eslint 8.1.1 
minimap 4.26.8 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
tablr 1.8.1 
```

**Comment by thehonkinggoose** [comment]
[Enter steps to reproduce:]

1. Load atom
2. See bug and profit?

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package 2.0.12


### Stack Trace

Failed to activate the atom-pair package

```
At Unexpected token )

SyntaxError: Unexpected token )
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-pair/lib/modules/session.coffee:1:1)
    at /packages/atom-pair/lib/modules/session.coffee:1:1)
    at /packages/atom-pair/lib/modules/session.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/atom-pair/lib/atom_pair.coffee:42:15)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-pair 2.0.12 
atom-runner 2.7.1 
atomify 0.6.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
double-tag 0.9.0 
file-icons 2.1.10 
git-time-machine 1.5.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.70.2 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-nginx 0.8.0 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-php 1.3.2 
linter-ui-default 1.6.4 
MagicPython 1.0.12 
nuclide 0.244.0 
nuclide-format-js 0.0.41 
php-cs-fixer 4.1.0 
platformio-ide-terminal 2.5.5 
react-es6-snippets 0.3.0 
react-snippets 0.9.0 
set-syntax 0.3.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

On a serious note this bug is very frustrating and it's getting to the point that I might have to uninstall the plugin if it's not fixed soon. It's slowing down my ability to do work. Please fix this as soon as possible.

**Comment by christhomas** [comment]
yup, I just got this error too "Unexpected token )"

**Comment by gczene** [comment]
same here
