### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeAttribute' of undefined

### ISSUE THREAD

**Issue by giovannibonetti** [pusher/atom-pair#39]
[Enter steps to reproduce below:]
1. Install package
2. Start new Session
3. Cmd + C
4. Press escape
5. Wait a few seconds

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v1.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'removeAttribute' of undefined

```
At /Users/gkbonetti/.atom/packages/atom-pair/lib/atom_pair.coffee:86

TypeError: Cannot read property 'removeAttribute' of undefined
  at Object.module.exports.AtomPair.disconnect (/Users/gkbonetti/.atom/packages/atom-pair/lib/atom_pair.coffee:86:32)
  at /Users/gkbonetti/.atom/packages/atom-pair/lib/atom_pair.coffee:209:51
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1063:22)
  at TextBuffer.module.exports.TextBuffer.release (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1088:14)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:268:19)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:475:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:452:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:695:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:739:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
     -2:48.2 core:cancel (atom-text-editor.editor.mini)
     -2:48.1 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:48.1 core:cancel (atom-text-editor.editor.is-focused)
     -2:19.4 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:17.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:17.1 core:cancel (atom-text-editor.editor.mini)
     -0:39.7 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:35.4 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:32.5 core:confirm (atom-text-editor.editor.mini)
     -0:32.5 AtomPair:start new pairing session (atom-text-editor.editor.is-focused)
     -0:28.9 AtomPair:copyid (div.session-id)
     -0:16.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:14.6 core:copy (atom-text-editor.editor.is-focused)
  2x -0:13.3 core:cancel (div.session-id)
     -0:01.6 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "*.html"
    ],
    "disabledPackages": [
      "linter-coffeelint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-flake8, v0.1.0
atom-lint, v0.20.1
atom-pair, v1.1.4
coffee-lint, v0.7.3
color-picker, v1.6.0
language-haskell, v1.0.0
language-jade, v0.3.0
language-scala, v1.1.0
minimap, v4.7.5
ruby-slim, v0.2.0

# Dev
No dev packages
```

**Comment by jpatel531** [comment]
Fixed in version 1.1.5 :)
