### ISSUE TITLE
Uncaught Error: Can't create a view for Promise instance. Please register a view provider.

### ISSUE THREAD

**Issue by shmink** [pusher/atom-pair#59]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.1
### Stack Trace

Uncaught Error: Can't create a view for Promise instance. Please register a view provider.

```
At C:\Users\Tommy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\view-registry.js:94

Error: Can't create a view for Promise instance. Please register a view provider.
  at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Tommy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\view-registry.js:94:15)
  at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Tommy\AppData\Local\atom\app-1.0.3\resources\app.asar\src\view-registry.js:65:21)
  at new SharePane (C:\Users\Tommy\.atom\packages\atom-pair\lib\modules\share_pane.coffee:38:55)
  at Object.module.exports.AtomPair.setUpLeadership (C:\Users\Tommy\.atom\packages\atom-pair\lib\atom_pair.coffee:161:21)
  at Object.module.exports.AtomPair.startPairing (C:\Users\Tommy\.atom\packages\atom-pair\lib\atom_pair.coffee:172:22)
  at C:\Users\Tommy\.atom\packages\atom-pair\lib\atom_pair.coffee:150:8
  at PresenceChannel.prototype.emit (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:3818:6)
  at C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:74:9
  at ConnectionManager.prototype.emit (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at message (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:3420:6)
  at Connection.prototype.emit (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at listeners.message (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:3048:8)
  at TransportConnection.prototype.emit (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at TransportConnection.prototype.onMessage (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (C:\Users\Tommy\.atom\packages\atom-pair\lib\pusher\pusher.js:2232:6)

```
### Commands

```
     -7:44.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.4.0 command-palette:toggle (div.settings-view.pane-item)
  3x -0:09.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 AtomPair:start new pairing session (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "retro-gruvbox"
    ]
  },
  "atom-pair": {}
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.1
color-picker, v2.0.11
file-icons, v1.6.2
linter, v1.3.0
linter-csslint, v0.0.14
linter-htmlhint, v0.0.17
linter-js-standard, v2.2.0
linter-php, v1.0.2
minimap, v4.12.2
retro-gruvbox, v1.0.4

# Dev
No dev packages
```

**Comment by lxcodes** [comment]
Same here error here /sadpanda

Atom Version: 1.0.3
System: Mac OS X 10.10

**Comment by angolini** [comment]
Same here
Ubuntu 14.10
$ atom -version
1.0.4

atom-pair@2.0.1

$apm -version
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.8
git 2.1.0

**Comment by brunowego** [comment]
+1 

Atom Version: 1.0.4
System: Mac OS X 10.10

**Comment by jpatel531** [comment]
Thanks for bringing this to my attention! I'll have a look at soon as I can

**Comment by DanielTamkin** [comment]
Got the Same thing here.
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.1

### Stack Trace

Uncaught Error: Can't create a view for Promise instance. Please register a view provider.

```
At C:\Users\Daniel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\view-registry.js:94

Error: Can't create a view for Promise instance. Please register a view provider.
  at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Daniel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\view-registry.js:94:15)
  at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Daniel\AppData\Local\atom\app-1.0.4\resources\app.asar\src\view-registry.js:65:21)
  at new SharePane (C:\Users\Daniel\.atom\packages\atom-pair\lib\modules\share_pane.coffee:38:55)
  at Object.module.exports.AtomPair.setUpLeadership (C:\Users\Daniel\.atom\packages\atom-pair\lib\atom_pair.coffee:161:21)
  at Object.module.exports.AtomPair.startPairing (C:\Users\Daniel\.atom\packages\atom-pair\lib\atom_pair.coffee:172:22)
  at C:\Users\Daniel\.atom\packages\atom-pair\lib\atom_pair.coffee:150:8
  at PresenceChannel.prototype.emit (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:3818:6)
  at C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:74:9
  at ConnectionManager.prototype.emit (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at message (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:3420:6)
  at Connection.prototype.emit (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at listeners.message (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:3048:8)
  at TransportConnection.prototype.emit (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
  at TransportConnection.prototype.onMessage (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (C:\Users\Daniel\.atom\packages\atom-pair\lib\pusher\pusher.js:2232:6)

```

### Commands

```
  2x -5:08.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -4:44.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:42.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:42.8.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -3:52.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 30x -2:31.7.0 core:backspace (atom-text-editor#atom-pair.hipchat_room_name.editor.mini.is-focused)
     -0:52.9.0 core:paste (atom-text-editor#atom-pair.slack_url.editor.mini.is-focused)
     -0:38.6.0 command-palette:toggle (div.settings-view.pane-item)
     -0:30.6.0 AtomPair:start new pairing session (div.settings-view.pane-item)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "file-icons"
    ]
  },
  "atom-pair": {
    "hipchat_room_name": "Test Test",
    "slack_url": " You dont need to see this "
  }
}
```

### Installed Packages

``` coffee
# User
atom-pair, v2.0.1
color-picker, v2.0.11
pigments, v0.9.3
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Comment by jpatel531** [comment]
I've managed to recreate it and found the root of the problem. I will push a new release shortly. Thanks everyone

**Comment by DanielTamkin** [comment]
Good to hear, @jpatel531

**Comment by jpatel531** [comment]
2.0.3 has been released, which should fix this. Originally this would happen on a page where there wasn't an active editor (e.g. a settings page). It should be all good now. Thanks again!

**Comment by lxcodes** [comment]
:+1: :clap: Thanks for the quick fix @jpatel531!

**Comment by DanielTamkin** [comment]
Damn fast quick fix, awesome stuff @jpatel531 !

**Comment by angolini** [comment]
It worked for me. Thanks a lot

**Comment by shmink** [comment]
Thanks for the quick fix @jpatel531
