### ISSUE TITLE
Uncaught TypeError: Cannot read property 'itemTitle' of undefined

### ISSUE THREAD

**Issue by szimek** [pusher/atom-pair#80]
I'm getting this error after I start a session and the other person tries to connect.

**Atom Version**: 1.0.8
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.9
### Stack Trace

Uncaught TypeError: Cannot read property 'itemTitle' of undefined

```
At /Users/szimek/.atom/packages/atom-pair/lib/modules/presence_indicator.coffee:48

TypeError: Cannot read property 'itemTitle' of undefined
  at Object.module.exports.PresenceIndicator.setActiveIcon (/Users/szimek/.atom/packages/atom-pair/lib/modules/presence_indicator.coffee:29:8)
  at User.module.exports.User.updatePosition (/Users/szimek/.atom/packages/atom-pair/lib/modules/user.coffee:57:23)
  at /Users/szimek/.atom/packages/atom-pair/lib/modules/session.coffee:153:36
  at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
  at Function.module.exports.SharePane.each (/Users/szimek/.atom/packages/atom-pair/lib/modules/share_pane.coffee:16:20)
  at /Users/szimek/.atom/packages/atom-pair/lib/modules/session.coffee:146:17
  at PresenceChannel.prototype.emit (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:3822:8)
  at /Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/Users/szimek/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```

**Comment by szimek** [comment]
It might be caused by the fact that I have disabled `tabs` package.

**Comment by jpatel531** [comment]
Ahh that's it. I'll make a patch that checks if `tabs` is disabled and if so then doesn't do that pencil icon. Cheers!
