### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by jeromemacias** [pusher/atom-pair#81]
Enter steps to reproduce below:  
1. Join a session

**Atom Version**: 1.0.8 
**System**: Mac OS X 10.10.5 
**Thrown From**:  atom-pair  https://github.com/pusher/atom-pair  package, v2.0.9 
### Stack Trace Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34 Error: Emitter has been disposed at Emitter.module.exports.Emitter.on /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15  
at Session.module.exports.Session.listenForDestruction  /Users/jmacias/.atom/packages/atom-pair/lib/modules/session.coffee:177:29  
at Session.module.exports.Session.startPairing  /Users/jmacias/.atom/packages/atom-pair/lib/modules/session.coffee:161:6  
at /Users/jmacias/.atom/packages/atom-pair/lib/modules/session.coffee:82:8 
at PresenceChannel.prototype.emit  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17  at PresenceChannel.prototype.handleEvent  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:3818:6  
at /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9 
at ConnectionManager.prototype.emit  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17  
at message  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6  
at Connection.prototype.emit  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17  
at listeners.message  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8  
at TransportConnection.prototype.emit  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17  
at TransportConnection.prototype.onMessage  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6  
at WebSocket.self.socket.ONMESSAGE  /Users/jmacias/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6      
```
### Commands

```
-2:42.3.0 AtomPair:join pairing session  atom-text-editor.editor  
-2:41.7.0 core:paste  atom-text-editor.editor.mini.is-focused  
-2:41.2.0 core:CONFIRM  atom-text-editor.editor.mini.is-focused  
-0:34.4.0 command-palette:toggle  atom-text-editor.editor.is-focused  
-0:31.5.0 core:move-down  atom-text-editor.editor.mini.is-focused  
-0:31.2.0 core:CONFIRM  atom-text-editor.editor.mini.is-focused  
-0:31.2.0 AtomPair:join pairing session  atom-text-editor.editor  
-0:27.3.0 command-palette:toggle  atom-text-editor.editor.is-focused  
-0:22.7.0 core:CONFIRM  atom-text-editor.editor.mini.is-focused  
-0:22.7.0 AtomPair:disconnect  atom-text-editor.editor 
 -0:12.9.0 command-palette:toggle  atom-text-editor.editor.is-focused 
 -0:04.6.0 core:move-down  atom-text-editor.editor.mini.is-focused  
-0:04.2.0 core:CONFIRM  atom-text-editor.editor.mini.is-focused  
-0:04.2.0 AtomPair:join pairing session  atom-text-editor.editor  
-0:03.3.0 core:paste  atom-text-editor.editor.mini.is-focused  
-0:02.8.0 core:CONFIRM  atom-text-editor.editor.mini.is-focused
```
### Config

```
 json { core : { themes :   unity-ui , one-dark-syntax  , projectHome : /Users/jmacias/Sites , excludeVcsIgnoredPaths : false, audioBeep : false } }     
```
### Installed Packages
- coffee 
#### User
- atom-pair, v2.0.9 
- auto-detect-indentation, v0.4.2 
- auto-indent, v0.5.0 
- autoclose-html, v0.18.0 
- autocomplete-modules, v1.1.0 
- autocomplete-sass, v0.1.0 
- change-case, v0.6.0 
- editorconfig, v1.1.1 
- file-icons, v1.6.9 
- indentation-indicator, v0.6.0 
- language-babel, v0.12.0 
- linter, v1.4.3 
- linter-eslint, v3.0.2 
- linter-jsonlint, v0.1.4 
- minimap, v4.13.2 
- project-manager, v1.16.0
- tree-view-OPEN-files, v0.2.4 
- unity-ui, v2.1.0 
#### Dev

No dev packages

**Comment by sygint** [comment]
I get this as well

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Ubuntu 15.04
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.9

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:34

Error: Emitter has been disposed
  at Emitter.module.exports.Emitter.on (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
  at Session.module.exports.Session.listenForDestruction (/home/adam/.atom/packages/atom-pair/lib/modules/session.coffee:177:29)
  at Session.module.exports.Session.startPairing (/home/adam/.atom/packages/atom-pair/lib/modules/session.coffee:161:6)
  at /home/adam/.atom/packages/atom-pair/lib/modules/session.coffee:82:8
  at PresenceChannel.prototype.emit (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:3818:6)
  at /home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/home/adam/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```

### Commands

```
     -5:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:44.6.0 AtomPair:start new pairing session (atom-pane.pane.active)
     -3:30.7.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
     -3:29.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:29.1.0 AtomPair:disconnect (atom-text-editor#AtomPair.editor)
  2x -3:25.1.0 AtomPair:start new pairing session (atom-text-editor#AtomPair.editor.is-focused)
  2x -0:53.7.0 AtomPair:join pairing session (atom-text-editor#AtomPair.editor.is-focused)
     -0:12.6.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
     -0:11.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.2.0 AtomPair:disconnect (atom-text-editor#AtomPair.editor)
     -0:09.2.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
  3x -0:06.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 AtomPair:join pairing session (atom-text-editor#AtomPair.editor)
     -0:02.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-make",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-java",
      "language-less",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-xml",
      "block-comment",
      "fold-comments",
      "vim-mode",
      "git-wip",
      "linter-csslint",
      "tree-view-git-status",
      "language-python",
      "language-mustache",
      "language-shellscript",
      "language-sql",
      "metrics",
      "open-on-github",
      "travis-ci-status",
      "tasks",
      "linter-scss-lint",
      "atom-ternjs"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "atom-pair": {
    "pusher_app_key": "28237b6b3d760cc4afa8",
    "pusher_app_secret": "35f835701610b1ca32a7"
  }
}
```

### Installed Packages

``` coffee
# User
apex-form-builder, v0.0.0
atom-alignment, v0.12.1
atom-jade, v0.3.0
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
atom-pair, v2.0.9
csslint, v1.1.4
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.9
git-diff-details, v0.20.0
git-log, v0.4.1
imdone-atom, v1.1.35
language-todo-extra-words, v0.2.0
linter, v1.4.3
linter-eslint, v3.0.2
linter-jade, v0.3.2
linter-jscs, v2.0.4
linter-write-good, v0.6.1
method-separator, v0.1.3
pigments, v0.12.0
project-manager, v1.16.0
seti-icons, v0.4.4
stash-tabs, v0.1.0

# Dev
No dev packages
```

**Comment by jpatel531** [comment]
2.0.10 should resolve this. Bizarre typo (or sneaky change to the API) - probably the former.

**Comment by OP-Klaus** [comment]
@jpatel531  I just got this error as well, but on line 77:

```
Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at Session.module.exports.Session.listenForDestruction (/Users/klausburton/.atom/packages/atom-pair/lib/modules/session.coffee:177:29)
    at Session.module.exports.Session.startPairing (/Users/klausburton/.atom/packages/atom-pair/lib/modules/session.coffee:161:6)
    at /Users/klausburton/.atom/packages/atom-pair/lib/modules/session.coffee:82:8
    at PresenceChannel.prototype.emit (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at PresenceChannel.prototype.handleEvent (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:3818:6)
    at /Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
    at ConnectionManager.prototype.emit (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at message (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
    at Connection.prototype.emit (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at listeners.message (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
    at TransportConnection.prototype.emit (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
    at TransportConnection.prototype.onMessage (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
    at WebSocket.self.socket.onmessage (/Users/klausburton/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)
```

**Comment by himanshu-jain16** [comment]
@jpatel531 I am also getting the same error on line 77
`Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (C:\Users\Himanshu\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:77:15)
    at Session.module.exports.Session.listenForDestruction (file:///C:/Users/Himanshu/.atom/packages/atom-pair/lib/modules/session.coffee:177:29)
    at Session.module.exports.Session.startPairing (file:///C:/Users/Himanshu/.atom/packages/atom-pair/lib/modules/session.coffee:161:6)
    at file:///C:/Users/Himanshu/.atom/packages/atom-pair/lib/modules/session.coffee:82:8
    at PresenceChannel.prototype.emit (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
    at PresenceChannel.prototype.handleEvent (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:3818:6)
    at C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:74:9
    at ConnectionManager.prototype.emit (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
    at message (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:3420:6)
    at Connection.prototype.emit (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
    at message (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:3048:8)
    at TransportConnection.prototype.emit (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:855:17)
    at TransportConnection.prototype.onMessage (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:2210:6)
    at WebSocket.self.socket.onmessage (C:\Users\Himanshu\.atom\packages\atom-pair\lib\pusher\pusher.js:2232:6)`

@OP-Klaus were you able to resolve the issue?
