### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clearIndicators' of undefined

### ISSUE THREAD

**Issue by TimoDJatomika** [pusher/atom-pair#82]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.9
### Stack Trace

Uncaught TypeError: Cannot read property 'clearIndicators' of undefined

```
At /home/timo/.atom/packages/atom-pair/lib/modules/session.coffee:157

TypeError: Cannot read property 'clearIndicators' of undefined
  at /home/timo/.atom/packages/atom-pair/lib/modules/session.coffee:157:11
  at PresenceChannel.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:3827:12)
  at /home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.9

# Dev
No dev packages
```

**Comment by TimoDJatomika** [comment]
I just want to try out the new atom-pair plugin and after my co-worker pasted the session ID into his atom editor I get an error message.

But the pair-programming is still working

**Comment by inancgumus** [comment]
The same here.

**Comment by jpatel531** [comment]
On it!

**Comment by inancgumus** [comment]
:+1: :+1:

**Comment by dougireton** [comment]
@jpatel531 is this still in progress? This issue prevents us from using Atom-Pair.

**Comment by jpatel531** [comment]
Sorry about the delay! Does this happen right at the beginning of the session, or when a collaborator leaves the session?

**Comment by dougireton** [comment]
At the beginning. I can't even establish a session. My pairing partner and I are behind a proxy if that makes any difference.

**Comment by TimoDJatomika** [comment]
I'm getting the error when I disconnect the session.

**Comment by elronalds** [comment]
It looks like this issue is still occurring in v2.0.10 of AtomPair

**Comment by Starefossen** [comment]
I get this issue constantly with latest version of Atom and AtomPair :disappointed:

**Comment by jlsjonas** [comment]
any update on this?

**Comment by TimoDJatomika** [comment]
@jlsjonas sorry I don't use atom any more

**Comment by jlsjonas** [comment]
@TimoDJatomika I was rather directing the question at the pusher team ;)
But out of curiosity... what are you using now?
