### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clearIndicators' of undefined

### ISSUE THREAD

**Issue by TimoDJatomika** [pusher/atom-pair#83]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.9
### Stack Trace

Uncaught TypeError: Cannot read property 'clearIndicators' of undefined

```
At /home/timo/.atom/packages/atom-pair/lib/modules/session.coffee:157

TypeError: Cannot read property 'clearIndicators' of undefined
  at /home/timo/.atom/packages/atom-pair/lib/modules/session.coffee:157:11
  at PresenceChannel.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:3827:12)
  at /home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/home/timo/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```
### Commands

```
     -2:42.6.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
  6x -2:41.1.0 core:backspace (atom-text-editor#AtomPair.editor.is-focused)
  2x -2:34.8.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -2:32 core:backspace (atom-text-editor#AtomPair.editor.is-focused)
     -2:30.7.0 window:reset-font-size (atom-text-editor#AtomPair.editor.is-focused)
     -2:26.7.0 core:backspace (atom-text-editor#AtomPair.editor.is-focused.autocomplete-active)
  2x -2:24.9.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
  8x -2:21.8.0 core:backspace (atom-text-editor#AtomPair.editor.is-focused.autocomplete-active)
  2x -2:15 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
  2x -2:10.3.0 core:move-up (atom-text-editor#AtomPair.editor.is-focused)
  9x -2:09.9.0 core:move-right (atom-text-editor#AtomPair.editor.is-focused)
     -2:07.3.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
  2x -2:05.7.0 core:move-up (atom-text-editor#AtomPair.editor.is-focused)
     -2:05.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -2:04.7.0 core:move-up (atom-text-editor#AtomPair.editor.is-focused)
     -1:57.1.0 core:move-left (atom-text-editor#AtomPair.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.9

# Dev
No dev packages
```

**Comment by TimoDJatomika** [comment]
duplication

**Comment by malonehedges** [comment]
@TimoDJatomika What was the solution to this? I just got this error.

**Comment by dougireton** [comment]
Dupe of #82
