### ISSUE TITLE
Uncaught TypeError: Cannot read property 'colour' of null

### ISSUE THREAD

**Issue by freshlogic** [pusher/atom-pair#84]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.10
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'colour' of null

```
At /Users/shawnmiller/.atom/packages/atom-pair/lib/modules/share_pane.coffee:271

TypeError: Cannot read property 'colour' of null
    at /Users/shawnmiller/.atom/packages/atom-pair/lib/modules/share_pane.coffee:271:28
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2137:27)
    at Selection.module.exports.Selection.screenRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:915:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:43:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
```
### Commands

```
     -4:46.2.0 core:save (atom-text-editor#AtomPair.editor.is-focused)
     -3:27.4.0 core:copy (atom-text-editor#AtomPair.editor.is-focused)
     -3:24.8.0 core:move-down (atom-text-editor#AtomPair.editor.is-focused)
  2x -3:24.4.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -3:23.8.0 core:move-up (atom-text-editor#AtomPair.editor.is-focused)
     -3:23.6.0 core:paste (atom-text-editor#AtomPair.editor.is-focused)
     -3:22.6.0 core:save (atom-text-editor#AtomPair.editor.is-focused)
     -2:45.8.0 core:copy (atom-text-editor#AtomPair.editor.is-focused)
  2x -2:41.2.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -2:41 core:paste (atom-text-editor#AtomPair.editor.is-focused)
     -2:40.1.0 core:save (atom-text-editor#AtomPair.editor.is-focused)
     -2:22.2.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
     -2:14.3.0 AtomPair:disconnect (atom-text-editor#AtomPair.editor)
     -1:55.4.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
  8x -1:50.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
 12x -1:47.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
language-ejs, v0.2.0
linter, v1.5.0
linter-jshint, v1.1.5

# Dev
No dev packages
```

**Comment by zwacky** [comment]
same here, disconnected from a connection then it appeared.

**Comment by sriharshakappala** [comment]
1. Disconnect from a pairing session.
2. Try saving a file or clicking on the file

**Atom Version**: 1.3.2
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.10

### Stack Trace

Uncaught TypeError: Cannot read property 'colour' of null

```
At /home/harsha/.atom/packages/atom-pair/lib/modules/share_pane.coffee:271

TypeError: Cannot read property 'colour' of null
    at /home/harsha/.atom/packages/atom-pair/lib/modules/share_pane.coffee:271:28
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/usr/share/atom/resources/app.asar/src/text-editor.js:2164:27)
    at Selection.module.exports.Selection.markerDidChange (/usr/share/atom/resources/app.asar/src/selection.js:929:26)
    at /usr/share/atom/resources/app.asar/src/selection.js:41:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:264:27)
    at /usr/share/atom/resources/app.asar/src/text-editor-marker.js:65:26
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:392:20)
    at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:338:12)
    at Marker.module.exports.Marker.setHeadPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:135:19)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadBufferPosition (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:175:32)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:185:19)
    at /usr/share/atom/resources/app.asar/src/cursor.js:65:31
    at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app.asar/src/cursor.js:674:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/usr/share/atom/resources/app.asar/src/cursor.js:63:19)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:1434:23
    at TextEditor.module.exports.TextEditor.moveCursors (/usr/share/atom/resources/app.asar/src/text-editor.js:1638:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1433:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/usr/share/atom/resources/app.asar/src/text-editor-component.js:662:25)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -1:04.6.0 core:move-left (atom-text-editor#AtomPair.editor.is-focused)
     -1:03.8.0 editor:select-to-beginning-of-word (atom-text-editor#AtomPair.editor.is-focused)
     -1:00.9.0 core:save (atom-text-editor#AtomPair.editor.is-focused.autocomplete-active)
     -1:00.5.0 editor:move-to-first-character-of-line (atom-text-editor#AtomPair.editor.is-focused)
     -1:00.3.0 editor:move-to-end-of-screen-line (atom-text-editor#AtomPair.editor.is-focused)
     -0:44.4.0 command-palette:toggle (atom-text-editor#AtomPair.editor.is-focused)
     -0:41.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:41.7.0 AtomPair:disconnect (atom-text-editor#AtomPair.editor)
     -0:37.9.0 pane:show-next-item (atom-text-editor#AtomPair.editor.is-focused)
  2x -0:36 core:move-up (atom-text-editor#AtomPair.editor.is-focused)
     -0:35.4.0 core:backspace (atom-text-editor#AtomPair.editor.is-focused)
  3x -0:35.1.0 core:save (atom-text-editor#AtomPair.editor.is-focused)
     -0:30.3.0 core:backspace (atom-text-editor#AtomPair.editor.is-focused)
  4x -0:15.1.0 pane:show-next-item (atom-text-editor#AtomPair.editor.is-focused)
     -0:12.7.0 core:save (atom-text-editor#AtomPair.editor.is-focused)
     -0:12.7.0 core:select-all (atom-text-editor#AtomPair.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "around-me"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.19
atom-pair, v2.0.10
autoclose-html, v0.19.0
file-icons, v1.6.13
language-haml, v0.23.14
language-rust, v0.4.5
linter, v1.11.3
minimap, v4.19.0
tool-bar, v0.1.10
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by a7madgamal** [comment]
+1

**Comment by MichaelJGW** [comment]
+1

**Comment by nicktogo** [comment]
+1

**Comment by FMA350** [comment]
+1
