### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of null

### ISSUE THREAD

**Issue by ghost** [pusher/atom-pair#86]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of null

```
At /Users/reflector/.atom/packages/atom-pair/lib/modules/session.coffee:151

TypeError: Cannot read property 'getTitle' of null
  at /Users/reflector/.atom/packages/atom-pair/lib/modules/session.coffee:151:34
  at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
  at Function.module.exports.SharePane.each (/Users/reflector/.atom/packages/atom-pair/lib/modules/share_pane.coffee:16:20)
  at /Users/reflector/.atom/packages/atom-pair/lib/modules/session.coffee:146:17
  at PresenceChannel.prototype.emit (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:3822:8)
  at /Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/Users/reflector/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```
### Commands

```
     -1:17.9.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.9.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.7.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.7.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.5.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.5.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.4.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.3.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.2.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:17.2.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:17 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:17 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:16.8.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:16.8.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
     -1:16.6.0 emmet:insert-formatted-line-break-only (atom-text-editor#AtomPair.editor.is-focused)
     -1:16.6.0 editor:newline (atom-text-editor#AtomPair.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "language-yaml"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.6.0
atom-pair, v2.0.10
emmet, v2.3.12
file-icons, v1.6.9
linter, v1.5.0
pigments, v0.13.2

# Dev
No dev packages
```

**Comment by SubJunk** [comment]
I just got this error when I tried to join my atom-pair instance from a Mac to Windows. The error showed up on the host (Windows) machine, and nothing happened on the Mac.

**Comment by aeischeid** [comment]
encountered with Linux to Windows pair session. Errors popped up on session host (Linux) and tab titles were blank on windows side.

**Comment by feitosa-daniel** [comment]
Same issue here, on Mac to Windows (host). Mac side popped successful connection. The session started successfully despite the errors from the Windows side. 

[host] Windows 7; Atom v1.9.9; Atom-pair v2.0.10
[client] Mac OS X 10.9.5; Atom v1.9.9; Atom-pair v2.0.10

**Comment by Augustin82** [comment]
Same error encountered just now.
[host] Linux Ubuntu 16.04; Atom v1.12.7; Atom-pair v2.0.10
[client] Linux Ubuntu 16.04; Atom v1.12.7; Atom-pair v2.0.10

**Comment by harin** [comment]
Doesn't work when host with
[host] macOS 10.12.2; Atom v1.13.1; Atom-pair v2.0.10

But I can join a session host by someone else

**Comment by johnazre** [comment]
I just connected two of my Windows 10 together with Doesn't work when host with Atom v1.13.1; Atom-pair v2.0.10. I also received this error. Has anyone seen any more issues than just the errors popping up? Is there any functionality issues?

**Comment by techopswhiz** [comment]
Why is it closed? Still an issue for me...

**Comment by kn100** [comment]
Hi,

I closed it as I recently look over maintenance of this plugin and believed it had since been resolved. Could you tell me a little about your setup?

**Comment by 3xcellent** [comment]
+1; just ran into this today as well, Windows -> Mac.

**Comment by kn100** [comment]
Please tell me about your setup. What version of Atom? Are you attempting to use your own Pusher details? What other plugins do you have installed?

**Comment by techopswhiz** [comment]
@kn100 I was using atom 1.2.2 on Ubuntu and trying to connect with a friend using atom on Windows 10. Both of us installed atom then just for using atom pair, and it was the only extension we installed outside the default extensions which come with the installation. I was trying to use my own credentials for pusher but we tried without it as well.
