### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setGrammar' of null

### ISSUE THREAD

**Issue by andreisebastianc** [pusher/atom-pair#87]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: "openSUSE 13.2
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'setGrammar' of null

```
At /home/andrei/.atom/packages/atom-pair/lib/modules/share_pane.coffee:58

TypeError: Cannot read property 'setGrammar' of null
  at /home/andrei/.atom/packages/atom-pair/lib/modules/share_pane.coffee:58:14
  at PresenceChannel.prototype.emit (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:3713:6)
  at PresenceChannel.prototype.handleEvent (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:3831:51)
  at /home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/home/andrei/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```
### Commands

```
     -8:59.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -8:57 core:select-all (atom-text-editor.editor.mini.is-focused)
     -8:56.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:52.4.0 core:undo (atom-text-editor.editor.is-focused)
  2x -8:51.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -8:44.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -8:43 core:move-down (atom-text-editor.editor.mini.is-focused)
     -8:42.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -8:41.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:41.6.0 AtomPair:start new pairing session (atom-text-editor.editor)
     -6:55.4.0 settings-view:uninstall-packages (atom-text-editor#AtomPair.editor.is-focused)
     -6:31.7.0 core:paste (atom-text-editor#atom-pair.pusher_app_key.editor.mini.is-focused)
     -6:29.6.0 core:undo (atom-text-editor#atom-pair.pusher_app_key.editor.mini.is-focused)
  2x -6:28.8.0 core:paste (atom-text-editor#atom-pair.pusher_app_secret.editor.mini.is-focused)
  2x -6:01.9.0 AtomPair:start new pairing session (atom-text-editor#AtomPair.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-pair": {
    "pusher_app_secret": "0cd04220d732c2131b80",
    "pusher_app_key": "d8abecee8a1e414adcfc"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10

# Dev
No dev packages
```

**Comment by nolman** [comment]
I experience this issue after the initial install of atom-pair it goes away after a reboot however it still happens if I host an atom pairing session and the other person leaves.
