### ISSUE TITLE
Uncaught TypeError: text.split is not a function

### ISSUE THREAD

**Issue by mattwynne** [pusher/atom-pair#90]
[Enter steps to reproduce below:]
1. Brand new install on Julien's machine and on Matt's machine
2. Julien starts a pairing session
3. Matt tries to join.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.10
### Stack Trace

Uncaught TypeError: text.split is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:772

TypeError: text.split is not a function
    at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:49:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:551:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:536:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:767:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:21)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:474:19)
    at /Users/matt/.atom/packages/atom-pair/lib/modules/share_pane.coffee:61:34
    at SharePane.module.exports.SharePane.withoutTrigger (/Users/matt/.atom/packages/atom-pair/lib/modules/share_pane.coffee:104:5)
    at /Users/matt/.atom/packages/atom-pair/lib/modules/share_pane.coffee:61:8
    at PresenceChannel.prototype.emit (/Users/matt/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
```
### Commands

```
     -0:44 core:move-down (input.hidden-input)
     -0:43.2.0 core:confirm (input.hidden-input)
     -0:43.2.0 AtomPair:join pairing session (input.hidden-input)
     -0:33.7.0 core:paste (input.hidden-input)
     -0:33 core:confirm (input.hidden-input)
     -0:17.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:13.6.0 core:confirm (input.hidden-input)
     -0:13.6.0 AtomPair:join pairing session (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:12.6.0 core:paste (input.hidden-input)
     -0:12.1.0 editor:move-to-first-character-of-line (input.hidden-input)
  3x -0:11.3.0 core:move-left (input.hidden-input)
     -0:10.5.0 core:delete (input.hidden-input)
     -0:09.8.0 core:move-left (input.hidden-input)
     -0:09.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:08.9.0 core:move-right (input.hidden-input)
     -0:08.1.0 core:confirm (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v2.0.10
cucumber, v0.5.0
language-gherkin, v1.0.2

# Dev
No dev packages
```

**Comment by mattwynne** [comment]
For reference, we were trying to open a Gherkin feature file.

**Comment by AngryPidgeon** [comment]
I'm getting this in some steps that return a promise.  It looks like whatever value the promise resolves to is potentially tripping up cucumber.  Like its trying to treat the value as a string?

**Comment by Starefossen** [comment]
A connected user got this error when I opened a new file.

**Comment by MeanderingCode** [comment]
Joined a session and over half of ~15 files the session starter opened resulted in this error and an empty file with the correct filename.  Probably 6 opened and were connected properly.  Properly opened files continued to work correctly.

I (session joiner) only opened one file, which displayed correctly in the session starter's atom instance.
