### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by ghost** [pusher/atom-pair#93]
[Enter steps to reproduce below:]
1. Start session
2. End Session

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-pair](https://github.com/pusher/atom-pair) package, v2.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Users/chrislewispac/.atom/packages/atom-pair/lib/modules/share_pane.coffee:150

TypeError: Cannot read property 'id' of null
  at SharePane.<anonymous> (/Users/chrislewispac/.atom/packages/atom-pair/lib/modules/share_pane.coffee:150:53)
  at SharePane.module.exports.SharePane.getTab (/Users/chrislewispac/.atom/packages/atom-pair/lib/modules/share_pane.coffee:258:10)
  at /Users/chrislewispac/.atom/packages/atom-pair/lib/modules/session.coffee:80:61
  at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
  at Function.module.exports.SharePane.each (/Users/chrislewispac/.atom/packages/atom-pair/lib/modules/share_pane.coffee:16:20)
  at /Users/chrislewispac/.atom/packages/atom-pair/lib/modules/session.coffee:80:21
  at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
  at /Users/chrislewispac/.atom/packages/atom-pair/lib/modules/session.coffee:79:11
  at /Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:3610:1
  at Object.Pusher.Util.objectApply (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:373:1)
  at Members.prototype.each (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:3609:13)
  at /Users/chrislewispac/.atom/packages/atom-pair/lib/modules/session.coffee:76:15
  at PresenceChannel.prototype.emit (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at PresenceChannel.prototype.handleEvent (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:3818:6)
  at /Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:74:9
  at ConnectionManager.prototype.emit (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at message (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:3420:6)
  at Connection.prototype.emit (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at listeners.message (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:3048:8)
  at TransportConnection.prototype.emit (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:855:17)
  at TransportConnection.prototype.onMessage (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:2210:6)
  at WebSocket.self.socket.onmessage (/Users/chrislewispac/.atom/packages/atom-pair/lib/pusher/pusher.js:2232:6)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.16
atom-jade, v0.3.0
atom-pair, v2.0.10
color-picker, v2.0.13
emmet, v2.3.13
highlight-selected, v0.10.1
imdone-atom, v1.1.51
linter-csslint, v1.1.0
linter-eslint, v4.0.0
linter-scss-lint, v2.4.0
minimap, v4.15.2
minimap-highlight-selected, v4.3.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by jpatel531** [comment]
hey there! do you have the 'tabs' package installed?

**Comment by ghost** [comment]
yes I do.
